<a href="https://colab.research.google.com/gist/siddharth-ncl-work/e465e7c88d2c2436152ac266e280de3b/lda_topic_modeling_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LDA (Topic Modeling)

In [121]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Download Data

In [122]:
!wget https://raw.githubusercontent.com/NarlikarLab/cisDIVERSITY/master/example.fa

--2021-02-20 02:20:21--  https://raw.githubusercontent.com/NarlikarLab/cisDIVERSITY/master/example.fa
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 215890 (211K) [text/plain]
Saving to: ‘example.fa.1’

example.fa.1        100%[===================>] 210.83K  --.-KB/s    in 0.03s   

2021-02-20 02:20:21 (7.89 MB/s) - ‘example.fa.1’ saved [215890/215890]



## Extract and Transform

In [123]:
_data={'seq_no.':[],'seq':[],'module':[]}
for line in open('example.fa','r').readlines():
  if '>' in line[0]:
    id=line.split('_')[0].split(':')[1]
    _data['seq_no.'].append(id)
    module=int(line.split('_')[1].split(':')[1])
    _data['module'].append(module)
  else:
    _data['seq'].append(line)
data=pd.DataFrame.from_dict(_data)
print(f'Dataset Size = {data.shape[0]}')
data.head()

Dataset Size = 1000


seq_no.                                                seq  module
0       0  GGAGGAGGAAGAGGCTGGGCCCCTGCTGTGTGGGGGCAAGTTCCCA...       0
1       1  CAAATACCCTGGGGTGCAATACGACTTATATCTCACGTATTGGAAG...       1
2       2  AACTAGGACACAGAAGTTGATCTAACGTAAACATCAAGAGCTTCCT...       1
3       3  CACAGCTGGGCCTGGTTGGTCTTTGTCCAGGGAACAATGGAGCGCC...       1
4       4  TTGTTTTATTTGTTTGTTGGGGGGCGGCGGGGAGCGACAGGGGAGT...       0

## Generate Motif Distribution

In [124]:
#m1
motif_data=-1000*np.ones(1000)
module1_data=data[data['module']==0]
module1_size=module1_data.shape[0]
motif_data[module1_data.index]=np.random.choice([0,1],size=module1_size,p=[0.8,0.2])
module2_data=data[data['module']==1]
module2_size=module2_data.shape[0]
motif_data[module2_data.index]=np.random.choice([0,1],size=module2_size,p=[0,1])
module3_data=data[data['module']==2]
module3_size=module3_data.shape[0]
motif_data[module3_data.index]=np.random.choice([0,1],size=module3_size,p=[1,0])
data['m1']=motif_data

In [125]:
#m2
motif_data=-1000*np.ones(1000)
module1_data=data[data['module']==0]
module1_size=module1_data.shape[0]
motif_data[module1_data.index]=np.random.choice([0,1],size=module1_size,p=[0,1])
module2_data=data[data['module']==1]
module2_size=module2_data.shape[0]
motif_data[module2_data.index]=np.random.choice([0,1],size=module2_size,p=[1,0])
module3_data=data[data['module']==2]
module3_size=module3_data.shape[0]
motif_data[module3_data.index]=np.random.choice([0,1],size=module3_size,p=[0.1,0.9])
data['m2']=motif_data

In [126]:
#m3
motif_data=-1000*np.ones(1000)
module1_data=data[data['module']==0]
module1_size=module1_data.shape[0]
motif_data[module1_data.index]=np.random.choice([0,1],size=module1_size,p=[0,1])
module2_data=data[data['module']==1]
module2_size=module2_data.shape[0]
motif_data[module2_data.index]=np.random.choice([0,1],size=module2_size,p=[1,0])
module3_data=data[data['module']==2]
module3_size=module3_data.shape[0]
motif_data[module3_data.index]=np.random.choice([0,1],size=module3_size,p=[1,0])
data['m3']=motif_data

In [127]:
#m4
motif_data=-1000*np.ones(1000)
module1_data=data[data['module']==0]
module1_size=module1_data.shape[0]
motif_data[module1_data.index]=np.random.choice([0,1],size=module1_size,p=[1,0])
module2_data=data[data['module']==1]
module2_size=module2_data.shape[0]
motif_data[module2_data.index]=np.random.choice([0,1],size=module2_size,p=[0.3,0.7])
module3_data=data[data['module']==2]
module3_size=module3_data.shape[0]
motif_data[module3_data.index]=np.random.choice([0,1],size=module3_size,p=[1,0])
data['m4']=motif_data

In [128]:
#m5
motif_data=-1000*np.ones(1000)
module1_data=data[data['module']==0]
module1_size=module1_data.shape[0]
motif_data[module1_data.index]=np.random.choice([0,1],size=module1_size,p=[1,0])
module2_data=data[data['module']==1]
module2_size=module2_data.shape[0]
motif_data[module2_data.index]=np.random.choice([0,1],size=module2_size,p=[1,0])
module3_data=data[data['module']==2]
module3_size=module3_data.shape[0]
motif_data[module3_data.index]=np.random.choice([0,1],size=module3_size,p=[0,1])
data['m5']=motif_data

In [129]:
module=0
print(data[data['module']==module]['m1'].value_counts(normalize=True))
print(data[data['module']==module]['m2'].value_counts(normalize=True))
print(data[data['module']==module]['m3'].value_counts(normalize=True))
print(data[data['module']==module]['m4'].value_counts(normalize=True))
print(data[data['module']==module]['m5'].value_counts(normalize=True))

0.0    0.795833
1.0    0.204167
Name: m1, dtype: float64
1.0    1.0
Name: m2, dtype: float64
1.0    1.0
Name: m3, dtype: float64
0.0    1.0
Name: m4, dtype: float64
0.0    1.0
Name: m5, dtype: float64


In [130]:
module=1
print(data[data['module']==module]['m1'].value_counts(normalize=True))
print(data[data['module']==module]['m2'].value_counts(normalize=True))
print(data[data['module']==module]['m3'].value_counts(normalize=True))
print(data[data['module']==module]['m4'].value_counts(normalize=True))
print(data[data['module']==module]['m5'].value_counts(normalize=True))

1.0    1.0
Name: m1, dtype: float64
0.0    1.0
Name: m2, dtype: float64
0.0    1.0
Name: m3, dtype: float64
1.0    0.742678
0.0    0.257322
Name: m4, dtype: float64
0.0    1.0
Name: m5, dtype: float64


In [131]:
module=2
print(data[data['module']==module]['m1'].value_counts(normalize=True))
print(data[data['module']==module]['m2'].value_counts(normalize=True))
print(data[data['module']==module]['m3'].value_counts(normalize=True))
print(data[data['module']==module]['m4'].value_counts(normalize=True))
print(data[data['module']==module]['m5'].value_counts(normalize=True))

0.0    1.0
Name: m1, dtype: float64
1.0    0.904762
0.0    0.095238
Name: m2, dtype: float64
0.0    1.0
Name: m3, dtype: float64
0.0    1.0
Name: m4, dtype: float64
1.0    1.0
Name: m5, dtype: float64


## Preprocessing

In [132]:
_data=data.copy()
_data['m1']=_data['m1'].map({1:'m1',0:'--'})
_data['m2']=_data['m2'].map({1:'m2',0:'--'})
_data['m3']=_data['m3'].map({1:'m3',0:'--'})
_data['m4']=_data['m4'].map({1:'m4',0:'--'})
_data['m5']=_data['m5'].map({1:'m5',0:'--'})

In [133]:
from gensim.corpora import Dictionary

_docs=_data[['m1','m2','m3','m4','m5']].values

In [134]:
_docs

array([['m1', 'm2', 'm3', '--', '--'],
       ['m1', '--', '--', 'm4', '--'],
       ['m1', '--', '--', 'm4', '--'],
       ...,
       ['m1', '--', '--', 'm4', '--'],
       ['--', 'm2', '--', '--', 'm5'],
       ['m1', '--', '--', 'm4', '--']], dtype=object)

In [135]:
docs=[]
def processDoc(seq):
  motifs=[]
  for m in seq:
    if 'm' in m:
      motifs.append(m)
  return motifs
for i,doc in enumerate(_docs):
  docs.append(processDoc(doc))

In [136]:
docs[:10]

[['m1', 'm2', 'm3'],
 ['m1', 'm4'],
 ['m1', 'm4'],
 ['m1', 'm4'],
 ['m1', 'm2', 'm3'],
 ['m1', 'm4'],
 ['m1'],
 ['m2', 'm3'],
 ['m1', 'm4'],
 ['m2', 'm3']]

In [137]:
dictionary=Dictionary(docs)
corpus = [dictionary.doc2bow(doc) for doc in docs]

In [138]:
for i,v in dictionary.items():
  print(i,v)

0 m1
1 m2
2 m3
3 m4
4 m5


In [139]:
corpus[:10]

[[(0, 1), (1, 1), (2, 1)],
 [(0, 1), (3, 1)],
 [(0, 1), (3, 1)],
 [(0, 1), (3, 1)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 1), (3, 1)],
 [(0, 1)],
 [(1, 1), (2, 1)],
 [(0, 1), (3, 1)],
 [(1, 1), (2, 1)]]

## LDA Model Training

In [169]:
from gensim.models import LdaModel,LdaMulticore

temp = dictionary[0]
id2word = dictionary.id2token
lda = LdaModel(corpus, id2word=id2word, alpha='auto',\
               eta='auto',num_topics=3, iterations=50, passes = 5)

In [170]:
lda.print_topics()

[(0, '0.588*"m1" + 0.406*"m4" + 0.003*"m3" + 0.003*"m2" + 0.000*"m5"'),
 (1, '0.441*"m2" + 0.437*"m3" + 0.095*"m1" + 0.027*"m4" + 0.000*"m5"'),
 (2, '0.497*"m5" + 0.421*"m2" + 0.039*"m1" + 0.022*"m4" + 0.021*"m3"')]

## LDA Model Evaluation of Training Data

In [171]:
pred_module=[]
for doc in corpus:
  top_topic=sorted(lda[doc],key=lambda x:-x[1])[0][0]
  pred_module.append(top_topic)
_data['pred_module']=pred_module

In [172]:
_data[_data['pred_module']==0][['module','pred_module']].value_counts()

module  pred_module
1       0              478
dtype: int64

In [173]:
_data[_data['pred_module']==1][['module','pred_module']].value_counts()

module  pred_module
0       1              480
dtype: int64

In [174]:
_data[_data['pred_module']==2][['module','pred_module']].value_counts()

module  pred_module
2       2              42
dtype: int64

In [175]:
class_dict={0:1,1:0,2:2}

In [176]:
_data['pred_module']=_data['pred_module'].map(class_dict)

### Accuracy Score (best performance is 1)

In [177]:
from sklearn.metrics import accuracy_score
accuracy_score(_data['module'],_data['pred_module'])

1.0

## K-Means Clustering 

In [149]:
X=data[['m1','m2','m3','m4','m5']].values
X

array([[1., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [150]:
from sklearn.cluster import KMeans

kmeans=KMeans(n_clusters=3,max_iter=10000,tol=1e-10,n_init=10,verbose=0).fit(X)

In [151]:
np.unique(kmeans.predict(X),return_counts=True)

(array([0, 1, 2], dtype=int32), array([518, 355, 127]))

## AffinityPropagation

In [152]:
from sklearn.cluster import AffinityPropagation

X=data[['m1','m2','m3','m4','m5']].values
kmeans=AffinityPropagation(max_iter=1000,convergence_iter=100).fit(X)

/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_affinity_propagation.py:226: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  "will not have any cluster centers.", ConvergenceWarning)


In [153]:
np.unique(kmeans.predict(X),return_counts=True)

/usr/local/lib/python3.6/dist-packages/sklearn/cluster/_affinity_propagation.py:423: ConvergenceWarning: This model does not have any cluster centers because affinity propagation did not converge. Labeling every sample as '-1'.
  "Labeling every sample as '-1'.", ConvergenceWarning)


(array([-1]), array([1000]))

## metric : adjusted rand index = 0 to 1